#!/bin/sh
set -eu
uwspkg info -a
uwspkg info -R uwspkg

origin=$(uwspkg info -q -o uwspkg)
if test 'base/uwspkg' != "${origin}"; then
	echo "origin: ${origin} - expect: base/uwspkg" >&2
	exit 1
fi

uwspkg info -l uwspkg

exit 0
