#!/bin/sh
set -eu

# load env

. /uwspkg/libexec/internal/env.export

sess=${UWSPKG_BUILD_SESSION}
pkgname=${UWSPKG_VERSION_NAME}
pkgorig=${UWSPKG_ORIGIN}
pkg_section=$(dirname ${pkgorig})

# pkgng env

export DEVELOPER_MODE='true'
export SYSLOG='false'

# generate metadata files

export UWSPKG_DESTDIR=/build/${sess}/$(cat /build/${sess}/.destdir)
export UWSPKG_BUILDDIR=$(mktemp -d -p /build/${sess} ${pkgname}-package-XXXXXXXX)

/uwspkg/libexec/internal/mkpkg

# save sources

mkdir -vp /uwspkg/repo/src/${pkg_section}

source_src=/build/${sess}/${pkgname}-source.tgz
source_dst=/uwspkg/repo/src/${pkg_section}/${pkgname}-source.tgz
install -v -m 0640 ${source_src} ${source_dst}

# pkg create

pkgdir=/uwspkg/repo/pkg/${pkg_section}
mkdir -vp ${pkgdir}

cd ${UWSPKG_BUILDDIR}
uwspkg create -v -o ${pkgdir} -m . -p pkg-plist -r ${UWSPKG_DESTDIR}
cd - >/dev/null

# save metadata

metadir_src=${UWSPKG_BUILDDIR}
metadir_dst=/uwspkg/repo/src/${pkg_section}/${pkgname}-meta

meta_dst=/uwspkg/repo/src/${pkg_section}/${pkgname}-meta.tgz
pkg_mdist=${metadir_src}/manifest.dist
pkgfn=${pkgdir}/${pkgname}.txz

uwspkg info -R --file ${pkgfn} >${pkg_mdist}

tar -C ${metadir_src} -czf ${meta_dst} ./
rm -rf ${metadir_dst}
mv -v ${metadir_src} ${metadir_dst}

# save package

oldwd=${PWD}
cd /uwspkg/repo
sha256sum src/${pkg_section}/${pkgname}-source.tgz \
	src/${pkg_section}/${pkgname}-meta.tgz \
	pkg/${pkg_section}/${pkgname}.txz >dist/${pkgname}.dist
	sha256sum -c dist/${pkgname}.dist
cd ${oldwd}

exit 0
