#!/bin/sh
set -eu
sess=${1:?'session name?'}
pkgname=${2:?'pkg name?'}
fetch_cmd=${3:?'fetch command?'}
builddir=$(mktemp -p /build/${sess} -d ${pkgname}-XXXXXXXX)
${fetch_cmd} BUILDDIR=${builddir}
basename ${builddir} >/build/${sess}/.builddir
exit 0
