#!/bin/sh
set -eu
fetch_cmd=${1:?'fetch command?'}
pkgname=${UWSPKG_VERSION_NAME}
builddir=$(mktemp -p /build -d ${pkgname}-XXXXXXXX)
${fetch_cmd} BUILDDIR=${builddir}
basename ${builddir} >/build/.builddir
exit 0
