#!/bin/sh
set -eu

prof=${1:?'profile name?'}
sess=${2:?'session name?'}
builddir=${3:?'build dir?'}
pkgsrc_dir=${4:?'package source dir?'}
pkgorig=${5:?'package origin?'}

srcdir=/etc/schroot/uwspkg-${prof}
dstdir=/etc/schroot/${sess}
cfgsrc=/etc/schroot/chroot.d/uwspkg-${prof}.conf
cfgdst=/etc/schroot/chroot.d/${sess}.conf

if test -d ${dstdir}; then
	echo "${dstdir}: already exists" >&2
	exit 1
fi

if test "X${dstdir}" = "X${srcdir}"; then
	echo "source and dest dir are the same: ${dstdir}" >&2
	exit 2
fi

install -o root -g root -d -m 0750 ${dstdir}
rsync -ax ${srcdir}/ ${dstdir}/

prof_fstab=${dstdir}/fstab
echo "${pkgsrc_dir}/${pkgorig}  /uwspkg/src/${pkgorig} none ro,bind 0 0" >>${prof_fstab}
echo "${builddir}/build/${sess} /build                 none rw,bind 0 0" >>${prof_fstab}

echo "[${sess}]" >${cfgdst}
tail -n +2 ${cfgsrc} | grep -Ev '^profile=' >>${cfgdst}
echo "profile=${sess}" >>${cfgdst}

exit 0
