#!/bin/sh
set -eu

builddir=${1:?'build dir?'}
pkgsrc_dir=${2:?'pkg source dir?'}

prof=${UWSPKG_PROFILE}
sess=${UWSPKG_BUILD_SESSION}
pkgorig=${UWSPKG_ORIGIN}
pkgvers=${UWSPKG_VERSION_NAME}

srcdir=/etc/schroot/uwspkg-${prof}
dstdir=/etc/schroot/${sess}
cfgsrc=/etc/schroot/chroot.d/uwspkg-${prof}.conf
cfgdst=/etc/schroot/chroot.d/${sess}.conf

if test -d ${dstdir}; then
	echo "${dstdir}: already exists" >&2
	exit 1
fi

if test "X${dstdir}" = "X${srcdir}"; then
	echo "source and dest dir are the same: ${dstdir}" >&2
	exit 2
fi

install -o root -g root -d -m 0750 ${dstdir}
rsync -ax ${srcdir}/ ${dstdir}/

cache_name="build/${pkgorig}/${pkgvers}"

prof_fstab=${dstdir}/fstab
echo "${pkgsrc_dir}/                  /uwspkg/src none ro,bind 0 0" >>${prof_fstab}
echo "${builddir}/build/${sess}       /build      none rw,bind 0 0" >>${prof_fstab}
echo "${builddir}/cache/${cache_name} /cache      none rw,bind 0 0" >>${prof_fstab}

mkdir -m 0770 /build/${sess}
chgrp uws /build/${sess}

mkdir -p -m 0770 /cache/${cache_name}
chgrp uws /cache/${cache_name}

echo "[${sess}]" >${cfgdst}
tail -n +2 ${cfgsrc} | grep -Ev '^profile=' >>${cfgdst}
echo "profile=${sess}" >>${cfgdst}

exit 0
