#!/bin/sh
set -eu

prof=${1:?'profile name?'}
sess=${2:?'session name?'}
builddir=${3:?'build dir?'}
libexec_dir=${4:?'libexec dir?'}
pkgsrc_dir=${5:?'package source dir?'}
pkgorig=${6:?'package origin?'}

srcdir=/etc/schroot/uwspkg-${prof}
dstdir=/etc/schroot/${sess}
cfgsrc=/etc/schroot/chroot.d/uwspkg-${prof}.conf
cfgdst=/etc/schroot/chroot.d/${sess}.conf

if test -d ${dstdir}; then
	echo "${dstdir}: already exists" >&2
	exit 1
fi

if test "X${dstdir}" = "X${srcdir}"; then
	echo "source and dest dir are the same: ${dstdir}" >&2
	exit 2
fi

install -o root -g root -d -m 0750 ${dstdir}
rsync -ax ${srcdir}/ ${dstdir}/

mkdir -m 0770 /build/${sess}
chgrp uws /build/${sess}

prof_fstab=${dstdir}/fstab

cat ${prof_fstab} >${prof_fstab}.tmp
cat ${prof_fstab}.tmp |
	sed "s#@SESSION@#${sess}#g" |
	sed "s#@PKGORIGIN@#${pkgorig}#g" |
	sed "s#@SRCDIR@#${pkgsrc_dir}#g" |
	sed "s#@BUILDDIR@#${builddir}#g" |
	sed "s#@LIBEXEC@#${libexec_dir}#g" >${prof_fstab}
rm -f ${prof_fstab}.tmp

echo "[${sess}]" >${cfgdst}
tail -n +2 ${cfgsrc} | grep -Ev '^profile=' >>${cfgdst}
echo "profile=${sess}" >>${cfgdst}

exit 0
